### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by DDeAlmeida** [near/near-contract-helper#533]
After upgrading Near Wallet and Near Contract Helper
Got this error :
Required this 3 datas in .env but nothing is mentionned in the Readme ...
ACCOUNT_CREATOR_KEY=XXX
ACCOUNT_CREATOR_KEYS=XXX
FUNDED_ACCOUNT_CREATOR_KEY=XXX

If i didn't put it got error on yarn start with FUNDED_ACCOUNT_CREATOR_KEY="undefined" etc

Then now got this one:

```
Starting child process with 'node app'
Round-robin account creation enabled. Yeee HAWWWW :)
/home/xxxx/near-contract-helper/middleware/createAccount.js:8
if (creatorKeysJson && creatorKeysJson.private_keys.length > 0) {
                                                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.<anonymous> (/home/blaze/near-contract-helper/middleware/createAccount.js:8:53)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/blaze/near-contract-helper/app.js:93:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Program node app exited with code 1

```

If i can have some help

**Comment by DDeAlmeida** [comment]
@MaximusHaximus @Patrick1904 
Hi guys, can you help me ? trying to update Near-Wallet from Guildnet (OpenShard Alliance).
thx

**Comment by MaximusHaximus** [comment]
@DDeAlmeida All 3 of these environment variables are expected to be parseable as JSON strings, and all 3 are _optional_, depending on the set of functionality that you are configuring the contract helper to provide.  

On our **mainnet** configuration, **only** `FUNDED_ACCOUNT_CREATOR_KEY` is set.
On our **testnet** configuration, **only** `ACCOUNT_CREATOR_KEYS` OR `ACCOUNT_CREATOR_KEY` is set.

#### `ACCOUNT_CREATOR_KEY`
This env var is used for testnet configurations to create new accounts. Testnet uses the `testnet` TLA _directly_ to create accounts, **because testnet accounts are funded for free.**

This env var should either be completely empty, **or** be structured like:
```javascript
{
  "account_id": "<root account ID responsible for creating sub-accounts>", // `testnet` on testnet
  "private_key": "ed25519:*******************************"
}
```
`account_id` must be the top-level-account that is directly responsible for creating new accounts
`private_key` must be a valid private key for that top-level account

#### `ACCOUNT_CREATOR_KEYS`
This env var is also used for testnet configurations to create new accounts, but is a high throughput option for direct `.testnet` account creation.  With only one access key, we are limited to a throughput of ~30 new account creations per minute.  By using multiple access keys, we can allow hundreds of new accounts to be created per minute by using a different key for each account creation transaction, round-robin style.  

This env var should either be completely empty, **or** be structured like:
```javascript
{
  "account_id": "<root account ID responsible for creating sub-accounts>", // `testnet` on testnet
  "private_keys": ["ed25519:*******************************","ed25519:*******************************",...]
}
```
`account_id` must be the top-level-account that is directly responsible for creating new accounts
`private_keys` must be **an array** of valid private keys for that top-level account


**It appears the error you are currently seeing is because the `ACCOUNT_CREATOR_KEYS` environment variable was set to valid JSON, but that JSON did not contain an array of keys under a `private_keys` property of the JSON.**

**If you are not configuring the contract helper for round-robin high-throughput account creation, you can resolve this issue by making sure that the `ACCOUNT_CREATOR_KEYS` environment variable is _empty_.  It is totally fine to only set `ACCOUNT_CREATOR_KEY`; this is the default low-throughput configuration.**

#### `FUNDED_ACCOUNT_CREATOR_KEY`
The env var is used for mainnet configurations to create new accounts.  Mainnet requires that a funding account call the `.near` top-level-account with a deposit attached in order to create new accounts.  This is because, unlike testnet, mainnet requires real NEAR to be provided to fund new accounts.


This env var should either be completely empty, **or** be structured like:
```javascript
{
  "account_id": "<account ID responsible for the creation of new accounts by cross-contract call to the .near top-level account>",
  "private_key": "ed25519:*******************************"
}
```
`account_id` must be an account with NEAR tokens available to be used to fund new accounts
`private_key` must be a valid private key for that funding account

I hope this shines some light on the problem -- I also dropped you a message on Discord; if you have any issues feel free to drop me a message there.

**Comment by DDeAlmeida** [comment]
Hello, thank for the replied.
I didn't received your Discord ping, you can also contact me on: Dav#5233, i'm on Near Discord ;)

We are in Guildnet so we use like testnet.
I filled ACCOUNT_CREATOR_KEY with account_id, private_key and public_key
But still having error

Maybe better to speak about it on Discord, and i will replied the answer here at the end.

Thank you again

**Comment by MaximusHaximus** [comment]
@DDeAlmeida 

I'm happy to have a real time chat to figure out what the issue is. :) 
I sent you a friend invite!

**Comment by DDeAlmeida** [comment]
Hello all, with the help of @MaximusHaximus 
I was able to start it.
But now when i try to load a profile i got this error:
![image](https://user-images.githubusercontent.com/52310650/144861518-44b55927-7332-4443-a787-a99ae5189af5.png)

Someone have an idea ?

**Comment by DDeAlmeida** [comment]
this error is due to .env = 
ssl=require 
after removing it all works !

Thank you @MaximusHaximus
