### ISSUE TITLE
Command migrate not found 

### ISSUE THREAD

**Issue by siddharthteli** [near/near-contract-helper#618]
- yarn migrate not working
- If i try to run yarn start directly it throws Error parsing ACCOUNT_CREATOR_KEYS='undefined .

**Comment by andy-haynes** [comment]
> yarn migrate not working

Apologies for the out-of-date documentation on this! We're no longer using `sequelize` in conjunction with Postgres for our database models as we have migrated to DynamoDB. Currently we do not have a local development implementation for working with DynamoDB but it is on my radar, it's just not a high priority as the internal team has access and we do not have many contributors working on code that touches the database. Please let me know if you're blocked on local development because of a lack of database and we can reevaluate its priority.

> If i try to run yarn start directly it throws Error parsing ACCOUNT_CREATOR_KEYS='undefined .

This should be a nonfatal error. So while it's annoying it should not actually interfere with anything. Is it affecting your local development?

**Comment by siddharthteli** [comment]
I have some progress now (Thanks to Dav from panda team). But i am still following  current readme & postgres db. My contract helper seems to be up & running but when i send curl command for account creation it throws an error. 

- Command i am running 
`curl -H "Content-Type: application/json" -XPOST http://0.0.0.0:3000/account --data '{"newAccountId": "nosuchuseryet", "newAccountPublicKey": "22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV"}'`

- Error on contract helper console (Image link)
https://postimg.cc/w1GCqhv8

Also, if you think this is redundant. Can you please guide me how to get started with DynamoDB.

**Comment by mieubrisse** [comment]
@andy-haynes not having a local setup for contract helper breaks [all the Kurtosis (localdev) setups](https://docs.near.org/docs/tools/kurtosis-localnet), because we spin up a NEAR node + contract helper + Wallet inside the Docker for folks who want it. This is currently being used by ~20 dApp developers in the #kurtosis channel on Discord; is there a way we can get a fix for this, or use an old version of the contract helper that will still work locally?

**Comment by andy-haynes** [comment]
@siddharthteli you're right that the contract helper is up and running, the error in your screenshot is coming from the RPC endpoint. I think you'd need to check the RPC documentation to see why it's failing, what RPC endpoint are you using? `nosuchuseryet` wouldn't be a valid account ID on testnet or mainnet.

Either way the error you're seeing is unrelated to the backend database, having a local DynamoDB instance would have no bearing on the behavior you're seeing. However I will still be adding local DynamoDB and updating the documentation to remove references to Postgres, which is no longer used.

**Comment by andy-haynes** [comment]
@mieubrisse I'll have a PR for local DynamoDB ready shortly, but in the meantime I don't think most developers would be hindered by not having access to a local database. The only thing affected should be the ability to create recovery methods which, while not ideal, should not be a real hindrance for dApp developers.

I'll update this issue when a local DynamoDB solution is ready and the documentation has been updated.

**Comment by mieubrisse** [comment]
Thanks @andy-haynes ; I'll let folks know about the recovery error (I saw this when creating an account) but doesn't sound like it's a hard blocker. I'll also stay tuned for updates on local DynamoDB!

**Comment by siddharthteli** [comment]
@andy-haynes , By type of RPC endpoint do you mean which network? I am running localnet node through nearup & nodeurl is set in .env file to `~/.near/config.json#rpc.addr` . Also, I am getting new error now- ` Error: [-32000] Server error: The node does not track the shard ID 0` . I thought this might be related to `tracked_shards` in ~/.near/config.json but modifying it didn't help.

**Comment by siddharthteli** [comment]
@mieubrisse , I ran the near cluster using Kurtosis & i assume you guys are using latest images of master branch repo's for explorer, contract helper, wallet etc.  Can you explain how using Kurtosis is different from running each node individually? I still want to run all nodes independently locally to understand whole flow better.

**Comment by andy-haynes** [comment]
@siddharthteli that is indeed all I meant by what RPC endpoint you were using 🙂

Since the problems outlined in this issue are not related to contract helper I'm going to close this in favor of #621.

**Comment by siddharthteli** [comment]
@andy-haynes , I assume there is some issue with local near node .  Do you have any idea what `Error: [-32000] Server error: The node does not track the shard ID 0`  might mean or someone who can help me debug it?

**Comment by andy-haynes** [comment]
@siddharthteli I would try the Discord server (maybe #dev-support) if you don't see anything relevant on StackOverflow or the CLI docs.
