### ISSUE TITLE
Error recovering account from passphrase in Kurtosis

### ISSUE THREAD

**Issue by gbouv** [near/near-contract-helper#657]
A user reported an issue with a pretty niche workflow of recovering an account from a passphrase.

Usecase:
1. Create an account and copy the passphrase somewhere
1. Close the window and open the wallet in a private navigation window
1. Click "Import an account" and then select "From a passphrase"
1. Input the passphrase from first step

And then there is failure on endpoint:
```
http://127.0.0.1:8330/account/recoveryMethods
```
with the following error:
```
blockNumberSignature did not match a signature of blockNumber=2750 from accountId=ad33af196d33cdc77918f6e2e94f59960ac2ef88ec6324bbec9b71f631518251
```

I noticed in the contract helper logs a lot of those errors:
```
2022-11-17 16:57:14.179 UTC [472] ERROR:  relation "daily_new_contracts_count" does not exist at character 86
2022-11-17 16:57:14.179 UTC [472] STATEMENT:  select "collected_for_day" as "date", "new_contracts_count" as "contractsCount" from "daily_new_contracts_count" order by "date"
2022-11-17 16:57:14.179 UTC [479] ERROR:  relation "daily_transactions_count" does not exist at character 76
2022-11-17 16:57:14.179 UTC [479] STATEMENT:  select "collected_for_day" as "date", "transactions_count" as "count" from "daily_transactions_count" order by "date"
2022-11-17 16:57:14.187 UTC [479] ERROR:  relation "daily_active_accounts_count" does not exist at character 87
2022-11-17 16:57:14.187 UTC [479] STATEMENT:  select "collected_for_day" as "date", "active_accounts_count" as "accountsCount" from "daily_active_accounts_count" order by "date"
2022-11-17 16:57:14.195 UTC [484] ERROR:  relation "daily_active_contracts_count" does not exist at character 89
2022-11-17 16:57:14.195 UTC [484] STATEMENT:  select "collected_for_day" as "date", "active_contracts_count" as "contractsCount" from "daily_active_contracts_count" order by "date"
2022-11-17 16:57:14.887 UTC [484] ERROR:  relation "daily_new_accounts_count" does not exist at character 84
2022-11-17 16:57:14.887 UTC [484] STATEMENT:  select "collected_for_day" as "date", "new_accounts_count" as "accountsCount" from "daily_new_accounts_count" order by "date"
2022-11-17 16:57:15.176 UTC [484] ERROR:  relation "daily_gas_used" does not exist at character 68
```

Could it be that the postgres DB is not properly seeded somehow and so it's unable to save the information from the account? If that seems likely, is there a script somewhere or an easy way to seed it?

Otherwise what could be the root cause for this issue?

**Comment by mieubrisse** [comment]
The `relation_daily_XXXX` does not exist have to do with stats (such as how many transactions are flowing through the network) for the Explorer; I don't think we need these.

The not-being-able-to-import thing is super super strange; I'm not sure why that's happening

**Comment by gbouv** [comment]
Gotcha, yeah we probably don't need stats, was just a wild guess. We probably need to expert from near to help us locate what piece we're missing here. @andy-haynes would you be able to help here? Or do you know someone who can?

**Comment by andy-haynes** [comment]
@gbouv  `blockNumberSignature did not match a signature...` would mean the signed block height (`blockNumberSignature`) was not signed using a full access key (or LAKs with specific methods created by wallet or multisig/2FA) belonging to the account for which recovery methods have been requested. This is how contract helper authenticates requests for anything touching the database.

Do you happen to have the data `POST`ed to the `/account/recoveryMethods` for one of these failed requests? If you can provide that and the corresponding contract helper error we should be able to trace this back.

**Comment by andy-haynes** [comment]
Hey @gbouv, so based on that screenshot and last request the issue actually looks like it's lag from the indexer. When you try to recover an account with passphrase, the wallet calls out to the indexer via contract helper. If the public key for that phrase can't be found in the indexer table, the wallet assumes the account does not exist on chain and so assumes it's an unfunded implicit account (which of course aren't created on testnet).

Can you tell whether the contract helper's indexer endpoint (`/publicKey/xxx/accounts`) is failing or just returning nothing? Does it work if you try again after waiting a few minutes?

**Comment by andy-haynes** [comment]
@gbouv I don't know much about indexer but you might have better luck raising an issue at https://github.com/near/near-indexer-for-explorer. For reference, [this is the query](https://github.com/near/near-contract-helper/blob/master/src/middleware/indexer.js#L97) that's causing the issue here (assuming that your call to `/publicKey/xxx/accounts` is returning an empty array, rather than an error describing a failure on the contract helper side).

Best I can do is try to break down the errors 🙂 

> 2022-12-01 10:04:41 Dec 01 09:04:41.380 ERROR indexer_for_explorer: Error occurred during DatabaseError(ForeignKeyViolation, "insert or update on table \"receipts\" violates foreign key constraint \"tx_receipt_fk\""): 

The first and last errors are due to the values of `originated_from_transaction_hash` not existing in the `transactions` table. So the creation of a corresponding record in `transactions` may be happening out of order or not be happening at all. It doesn't seem to be directly related to the issue you're seeing but it could be breaking the flow responsible for getting the account's access key into the database.

> 2022-12-01 10:06:19 Dec 01 09:06:19.333 ERROR indexer_for_explorer: Error occurred during DatabaseError(ForeignKeyViolation, "insert or update on table \"account_changes\" violates foreign key constraint \"account_id_fk\""): 

This second error indicates `guillaume2.test.near` was not created on chain or was otherwise erroneously absent the `accounts` table.

So I don't see anything here that stands out as being particularly problematic, but being ignorant of the workflow here it may be breaking something downstream. If you want to troubleshoot on your own, you could try reproducing the issue then querying the `accounts` and `access_keys` tables for the account you are trying to recover to see where things are going wrong.
